#!/usr/bin/env python3
"""Render a readable Chinese AI Hot Radar poster from scored news cards."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import textwrap
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont


FONT_CANDIDATES = [
    "/System/Library/Fonts/STHeiti Medium.ttc",
    "/System/Library/Fonts/PingFang.ttc",
    "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
    "/System/Library/Fonts/Supplemental/Songti.ttc",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render AI Hot Radar Chinese poster")
    parser.add_argument("--items-json", required=True, help="JSON file with poster items")
    parser.add_argument("--output", required=True, help="Output PNG path")
    parser.add_argument("--background", help="Optional background image generated by an image API")
    parser.add_argument("--title", default="今日 AI 热点雷达")
    parser.add_argument("--subtitle", default="过去 24 小时最值得关注的 5 件事")
    parser.add_argument("--footer", default="数据源：AI HOT / 官方 RSS / GitHub")
    parser.add_argument("--time-window", default="")
    return parser.parse_args()


def font(size: int) -> ImageFont.FreeTypeFont:
    for path in FONT_CANDIDATES:
        if Path(path).exists():
            return ImageFont.truetype(path, size=size)
    return ImageFont.load_default(size=size)


def load_items(path: Path) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(data, dict):
        data = data.get("items", [])
    if not isinstance(data, list) or not data:
        raise SystemExit("items-json must contain a non-empty list")
    return data[:5]


def make_canvas(background: str | None) -> Image.Image:
    width, height = 720, 1280
    if background:
        bg = Image.open(background).convert("RGB").resize((width, height))
        bg = bg.filter(ImageFilter.GaussianBlur(radius=10))
        veil = Image.new("RGBA", (width, height), (248, 253, 252, 218))
        return Image.alpha_composite(bg.convert("RGBA"), veil)

    base = Image.new("RGBA", (width, height), (246, 252, 250, 255))
    draw = ImageDraw.Draw(base)
    draw.polygon([(520, 0), (720, 0), (720, 1280), (470, 1280)], fill=(103, 211, 201, 90))
    draw.ellipse((450, 50, 870, 470), fill=(67, 180, 170, 45))
    draw.ellipse((-160, 820, 260, 1260), fill=(0, 135, 125, 28))
    return base


def rounded(draw: ImageDraw.ImageDraw, box: tuple[int, int, int, int], radius: int, fill, outline=None, width=1) -> None:
    draw.rounded_rectangle(box, radius=radius, fill=fill, outline=outline, width=width)


def wrap_cjk(text: str, width: int) -> str:
    text = str(text).strip()
    if len(text) <= width:
        return text
    return "\n".join(textwrap.wrap(text, width=width, break_long_words=True, replace_whitespace=False)[:2])


def draw_poster(args: argparse.Namespace) -> Path:
    items = load_items(Path(args.items_json))
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)

    image = make_canvas(args.background)
    draw = ImageDraw.Draw(image)

    title_font = font(58)
    subtitle_font = font(23)
    label_font = font(18)
    score_font = font(34)
    item_title_font = font(25)
    item_judgment_font = font(20)
    footer_font = font(17)

    draw.text((58, 92), args.title, fill=(16, 105, 99), font=title_font)
    draw.text((60, 174), args.subtitle, fill=(37, 67, 76), font=subtitle_font)
    time_text = args.time_window or dt.datetime.now().strftime("%Y-%m-%d %H:%M Asia/Shanghai")
    draw.text((60, 210), time_text, fill=(94, 117, 123), font=label_font)
    rounded(draw, (525, 86, 660, 124), 19, fill=(16, 128, 118, 220))
    draw.text((548, 96), "AI NEWS", fill=(255, 255, 255), font=label_font)

    y = 300
    for idx, item in enumerate(items, 1):
        score = int(item.get("score", 75))
        title = wrap_cjk(item.get("title") or item.get("chinese_title") or "AI 热点", 18)
        judgment = str(item.get("judgment") or item.get("one_sentence") or "值得关注").strip()[:16]

        rounded(draw, (56, y, 664, y + 135), 28, fill=(255, 255, 255, 232), outline=(196, 235, 230, 255), width=2)
        rounded(draw, (82, y + 28, 164, y + 92), 18, fill=(13, 143, 132, 235))
        draw.text((96, y + 36), f"{score}", fill=(255, 255, 255), font=score_font)
        draw.text((107, y + 76), "/100", fill=(224, 255, 252), font=label_font)
        draw.text((188, y + 26), title, fill=(26, 48, 58), font=item_title_font, spacing=4)
        draw.text((188, y + 92), judgment, fill=(11, 120, 112), font=item_judgment_font)
        draw.text((604, y + 28), f"0{idx}", fill=(153, 180, 184), font=label_font)
        y += 155

    rounded(draw, (58, 1112, 662, 1184), 24, fill=(10, 77, 74, 225))
    draw.text((88, 1132), args.footer, fill=(231, 255, 252), font=footer_font)
    draw.text((88, 1158), "自动抓取、去重、评分，仅供信息参考", fill=(178, 224, 219), font=footer_font)

    image.convert("RGB").save(output, format="PNG", optimize=True)
    print(str(output))
    return output


def main() -> int:
    draw_poster(parse_args())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
