#!/usr/bin/env python3
"""Render a detailed, readable Chinese AI Hot Radar poster from news cards."""

from __future__ import annotations

import argparse
import datetime as dt
import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont


FONT_CANDIDATES = [
    "/System/Library/Fonts/STHeiti Medium.ttc",
    "/System/Library/Fonts/PingFang.ttc",
    "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
    "/System/Library/Fonts/Supplemental/Songti.ttc",
]

CATEGORY_LABELS = {
    "ai-models": "模型",
    "ai-products": "产品",
    "industry": "行业",
    "paper": "论文",
    "tip": "观点",
    "open-source": "开源",
    "unknown": "资讯",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render AI Hot Radar Chinese poster")
    parser.add_argument("--items-json", required=True, help="JSON file with poster items")
    parser.add_argument("--output", required=True, help="Output PNG path")
    parser.add_argument("--background", help="Optional background image generated by an image API")
    parser.add_argument("--title", default="今日 AI 热点雷达")
    parser.add_argument("--subtitle", default="过去 24 小时最值得关注的 AI 资讯")
    parser.add_argument("--footer", default="数据源：AI HOT / 官方 RSS / GitHub")
    parser.add_argument("--time-window", default="")
    parser.add_argument("--max-items", type=int, default=4, help="Detailed poster works best with 3-4 items")
    return parser.parse_args()


def font(size: int) -> ImageFont.FreeTypeFont:
    for path in FONT_CANDIDATES:
        if Path(path).exists():
            return ImageFont.truetype(path, size=size)
    return ImageFont.load_default(size=size)


def load_items(path: Path, limit: int) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(data, dict):
        data = data.get("items", [])
    if not isinstance(data, list) or not data:
        raise SystemExit("items-json must contain a non-empty list")
    return data[: max(1, min(limit, 5))]


def make_canvas(background: str | None) -> Image.Image:
    width, height = 720, 1280
    if background:
        bg = Image.open(background).convert("RGB").resize((width, height))
        bg = bg.filter(ImageFilter.GaussianBlur(radius=14))
        veil = Image.new("RGBA", (width, height), (247, 251, 248, 232))
        image = Image.alpha_composite(bg.convert("RGBA"), veil)
    else:
        image = Image.new("RGBA", (width, height), (247, 251, 248, 255))

    draw = ImageDraw.Draw(image)
    draw.rectangle((0, 0, 720, 1280), fill=(248, 252, 249, 238))
    draw.polygon([(510, 0), (720, 0), (720, 1280), (465, 1280)], fill=(0, 119, 105, 28))
    draw.ellipse((430, 40, 900, 520), fill=(24, 181, 159, 26))
    draw.ellipse((-180, 780, 280, 1270), fill=(16, 104, 96, 20))
    return image


def rounded(draw: ImageDraw.ImageDraw, box: tuple[int, int, int, int], radius: int, fill, outline=None, width=1) -> None:
    draw.rounded_rectangle(box, radius=radius, fill=fill, outline=outline, width=width)


def normalize_text(text: str) -> str:
    text = " ".join(str(text or "").replace("\n", " ").split()).strip()
    return text


def wrap_pixels(text: str, draw: ImageDraw.ImageDraw, draw_font, max_width: int, max_lines: int) -> str:
    text = normalize_text(text)
    if not text:
        return ""
    lines: list[str] = []
    current = ""
    for char in text:
        candidate = current + char
        if draw.textlength(candidate, font=draw_font) <= max_width:
            current = candidate
            continue
        if current:
            lines.append(current)
        current = char
        if len(lines) >= max_lines:
            break
    if len(lines) < max_lines and current:
        lines.append(current)
    overflow = "".join(lines) != text and len(lines) >= max_lines
    if overflow and lines:
        last = lines[-1].rstrip("。,.，、 ")
        while draw.textlength(last + "…", font=draw_font) > max_width and last:
            last = last[:-1]
        lines[-1] = last + "…"
    return "\n".join(lines[:max_lines])


def truncate_pixels(text: str, draw: ImageDraw.ImageDraw, draw_font, max_width: int) -> str:
    text = normalize_text(text)
    if draw.textlength(text, font=draw_font) <= max_width:
        return text
    while text and draw.textlength(text + "…", font=draw_font) > max_width:
        text = text[:-1]
    return text + "…"


def item_value(item: dict, *keys: str, default: str = "") -> str:
    for key in keys:
        value = item.get(key)
        if value:
            return str(value)
    return default


def category_label(value: str) -> str:
    value = str(value or "unknown")
    return CATEGORY_LABELS.get(value, value[:6] or "资讯")


def draw_badge(draw: ImageDraw.ImageDraw, xy: tuple[int, int], text: str, bg, fg, badge_font) -> int:
    x, y = xy
    bbox = draw.textbbox((x, y), text, font=badge_font)
    width = bbox[2] - bbox[0] + 24
    rounded(draw, (x, y, x + width, y + 30), 15, fill=bg)
    draw.text((x + 12, y + 5), text, fill=fg, font=badge_font)
    return width


def draw_poster(args: argparse.Namespace) -> Path:
    items = load_items(Path(args.items_json), args.max_items)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)

    image = make_canvas(args.background)
    draw = ImageDraw.Draw(image)

    title_font = font(52)
    subtitle_font = font(22)
    label_font = font(16)
    badge_font = font(15)
    score_font = font(32)
    item_title_font = font(23)
    summary_font = font(17)
    meta_font = font(15)
    footer_font = font(16)

    draw.text((52, 76), args.title, fill=(9, 91, 82), font=title_font)
    draw.text((56, 148), args.subtitle, fill=(31, 56, 66), font=subtitle_font)
    time_text = args.time_window or dt.datetime.now().strftime("%Y-%m-%d %H:%M Asia/Shanghai")
    draw.text((56, 184), time_text, fill=(94, 111, 118), font=label_font)
    rounded(draw, (526, 76, 662, 116), 20, fill=(9, 116, 105, 232))
    draw.text((548, 86), "AI NEWS", fill=(255, 255, 255), font=label_font)

    y = 238
    card_h = 202 if len(items) <= 4 else 166
    gap = 20 if len(items) <= 4 else 14
    for idx, item in enumerate(items, 1):
        score = int(float(item.get("score", 75)))
        title = wrap_pixels(item_value(item, "title", "chinese_title", default="AI 热点"), draw, item_title_font, 440, 2)
        summary = wrap_pixels(
            item_value(item, "summary", "one_sentence", "why_it_matters", default="值得关注的 AI 动态。"),
            draw,
            summary_font,
            440,
            2,
        )
        source = truncate_pixels(item_value(item, "source", "source_name", default="AI HOT"), draw, meta_font, 220)
        published = item_value(item, "published_at", "published", "time", default="时间待确认")[:16].replace("T", " ")
        cat = category_label(item_value(item, "category", "type", default="unknown"))

        rounded(draw, (46, y, 674, y + card_h), 28, fill=(255, 255, 255, 240), outline=(188, 228, 221, 255), width=2)
        rounded(draw, (72, y + 28, 152, y + 88), 18, fill=(5, 133, 120, 240))
        draw.text((86, y + 34), f"{score}", fill=(255, 255, 255), font=score_font)
        draw.text((96, y + 70), "/100", fill=(220, 255, 250), font=badge_font)

        draw_badge(draw, (176, y + 24), cat, bg=(226, 247, 243, 255), fg=(3, 111, 100), badge_font=badge_font)
        draw.text((612, y + 26), f"0{idx}", fill=(149, 173, 177), font=label_font)
        draw.text((176, y + 60), title, fill=(18, 41, 52), font=item_title_font, spacing=2)
        draw.text((176, y + 120), summary, fill=(67, 82, 90), font=summary_font, spacing=3)

        meta_y = y + card_h - 38
        draw.text((72, meta_y), f"发布时间：{published}", fill=(88, 106, 112), font=meta_font)
        draw.text((380, meta_y), f"来源：{source}", fill=(88, 106, 112), font=meta_font)

        y += card_h + gap

    footer_top = 1114
    rounded(draw, (52, footer_top, 668, footer_top + 92), 26, fill=(6, 74, 68, 232))
    draw.text((82, footer_top + 22), args.footer, fill=(231, 255, 252), font=footer_font)
    draw.text((82, footer_top + 52), "字段：标题 / 摘要 / 发布时间 / 来源 / 类型 / 重要度评分", fill=(180, 226, 220), font=footer_font)

    image.convert("RGB").save(output, format="PNG", optimize=True)
    print(str(output))
    return output


def main() -> int:
    draw_poster(parse_args())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
